version: '3.8'

services:
  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/?ssl=false

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

  mongo:
    image: mongo:4.4
    command: mongod --bind_ip_all --noauth
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata: